fix: add documentation of learner recommendations
edx/edx-recommendations pull request #1
Opened 2023-05-23 06:46 UTC by ahtesham-quraish

Description:
Need to add the ADR and readme file which would explain the purpose and how to use it.

Related to : https://2u-internal.atlassian.net/browse/VAN-1396

2023-05-25 08:14 UTC, mubbsharanwar requested changes
There also should be a section in README file **How to test locally** or should be a confluence doc and linked here.

2023-05-25 08:14 UTC, mubbsharanwar commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] Unit tests added/updated
Should unit test not be part of PR? Why we are removing this from check list?

2023-05-25 08:14 UTC, mubbsharanwar commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] Manual testing instructions provided
Also It would be nice if contributor add steps to test changes locally.

2023-05-25 08:14 UTC, mubbsharanwar commented on README.rst
> +Unit Testing
Can we not run this repo's tests under its shell or environment? I think we need to update this section that how contributor can add and run unit test for this rep using its environment.

2023-05-25 08:23 UTC, ahtesham-quraish commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] Unit tests added/updated
yeah we should add it.

2023-05-26 07:08 UTC, mubbsharanwar commented on README.rst
> +    make install-local
For now we should remove make commands because we have not make file at this point. We will add this once we create make file in this project.

2023-05-26 07:14 UTC, mubbsharanwar approved these changes

2023-05-26 09:19 UTC, merged